version: '3.9'
services:
  app:
    container_name: fizzbuzz_go
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - fizzbuzz-net
  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - fizzbuzz-net

networks:
  fizzbuzz-net:
    driver: bridge

volumes:
  redis-data:
    driver: local