version: '3.9'
services:
  app:
    container_name: fizzbuzz_go
    build: .
    depends_on:
      - redis
  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
    driver: local